---
language: python
python: "2.7"

os: linux

addons:
  apt:
    packages:
    - python-apt

install:
  - pip install ansible
  - touch ansible.cfg
  - printf '[defaults]\nroles_path = ../' > ansible.cfg

script:

  # Check the role's syntax
  - "ansible-playbook tests/travis-test.yml -i tests/travis-inventory --syntax-check"

  # Run the role with ansible-playbook
  - "ansible-playbook tests/travis-test.yml -i tests/travis-inventory --connection=local"

  # Run the role again to check for idempotence
  - >
    ansible-playbook tests/travis-test.yml -i tests/travis-inventory --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check if vim installed successfully
  - "if [[ ! $(vim --version | grep 8.2) ]]; then echo 'vim did not install successfully'; exit 1; fi"

  # Check if vim was compiled with the specified dependencies
  - "if [[ ! $(vim --version | grep +python3) ]]; then echo 'vim did not compile with python3 successfully'; exit 1; fi"
  - "if [[ ! $(vim --version | grep +ruby) ]]; then echo 'vim did not compile with ruby successfully'; exit 1; fi"
  - "if [[ ! $(vim --version | grep +lua) ]]; then echo 'vim did not compile with lua successfully'; exit 1; fi"
  - "if [[ ! $(vim --version | grep +perl) ]]; then echo 'vim did not compile with perl successfully'; exit 1; fi"
  - "if [[ ! $(vim --version | grep +multi_byte) ]]; then echo 'vim did not compile with multi_byte successfully'; exit 1; fi"
  - "if [[ ! $(vim --version | grep +cscope) ]]; then echo 'vim did not compile with cscope successfully'; exit 1; fi"

  - "echo 'vim installed and compiled successfully'"
